version: '3.3'

services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      REDIS_HOST : redis
    depends_on:
      - redis

  redis:
    image: redis:5.0.7-alpine
    command: redis-server --appendonly yes
    volumes:
      - /data
